name: test

on:
  - push
  - pull_request
  - workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.2
      - name: Install
        run: npm install
      - name: Run lint
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.2
      - name: Install
        run: npm install
      - name: Run typecheck
        run: npm run typecheck

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version:
          - 20.10.0
          - 21.x
          - 22.x
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.2
      - name: Install
        run: npm run install
      - name: Run tests
        run: npm run test
